# Étape de build
FROM node:latest AS build

WORKDIR /frontend

# Copier les fichiers de configuration npm
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tous les fichiers du frontend
COPY . .

# Build de l'application frontend
RUN npm run build

# Utilisation d'une image Nginx pour servir le contenu
FROM nginx:alpine

# Copier les fichiers buildés du frontend dans le répertoire nginx
COPY --from=build /frontend/dist /usr/share/nginx/html

# Exposer le port 80 pour Nginx
EXPOSE 80

# Configuration du démarrage de Nginx en tant que démon
CMD ["nginx", "-g", "daemon off;"]