version: '3.7'

services:
  front-end:
    image: beddarrbiha/reby_pepiniere:latest
    ports:
      - "8080:80"
    networks:
      - app-network

  back-end:
    depends_on:
      mysql:
        condition: service_healthy
    image: beddarrbiha/back-end:latest
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=projet
      - DB_PORT=3306
    stdin_open: true
    tty: true  
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=projet
      #- MYSQL_ALLOW_EMPTY_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u rebiha --password=password"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s  
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front-end
      - back-end
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      mysql:
        condition: service_healthy
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "6060:80"
    environment:
      - PMA_HOST=mysql  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: