version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_DATABASE=""
    ports:
      - 3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  
  backend:
    depends_on:
      - mysqldb
    build: backEnd/.
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mysqldb
      - DB_USER="root"
      - DB_PASSWORD=""
      - DB_NAME="projet"
      - DB_PORT=3306
      #- CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend

  frontend:
    build:
      context: ./app
    ports:
      - 8080
    networks:
      - frontend 