# Étape de build
FROM node:latest

WORKDIR /frontend

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

EXPOSE 8080

#RUN npm run build

# Utiliser une image Nginx pour servir le contenu
FROM nginx:alpine

COPY --from=0 /frontend /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]