version: '3'
services:
  front-end:
    image: beddarrbiha/reby_pepiniere:latest
    ports:
      - "8080:8080"

  back-end:
    image: docker push beddarrbiha/back-end:latest
    ports:
      - "3000:3000"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "projet"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
