version: '3.7'

services:
  front-end:
    image: beddarrbiha/reby_pepiniere:latest
    ports:
      - "8081:80"
    networks:
      - app-network

  back-end:
    image: beddarrbiha/reby_pepiniere:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: projet
      MYSQL_USER: rebiha
      MYSQL_PASSWORD: "root_password"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front-end
      - back-end
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: