# Utiliser l'image officielle de Node.js
FROM node

# Définir le répertoire de travail
WORKDIR /backend

# Copier les fichiers de configuration npm
COPY backend/package.json backend/package-lock.json ./

# Installer les dépendances
RUN npm install

# Copier tous les fichiers du backend
COPY backend .

# Exposer le port pour l'application backend
EXPOSE 3000

# Démarrer l'application backend avec Node.js
CMD ["node", "server.js"]