# Utiliser l'image officielle de Node.js
FROM node:16

# Définir le répertoire de travail
WORKDIR /backend

# Copier les fichiers de configuration npm
COPY package*.json ./

# Installer les dépendances
RUN rm package-lock.json && npm install

# Copier tous les fichiers du backend
COPY . .

# Exposer le port pour l'application backend
EXPOSE 3000

# Démarrer l'application backend avec Node.js
CMD ["node", "server.js"]